// utils/affixOptions.js

const weaponAffixes = [
    { affix: 'Maximum Life', range: [638, 873] },
    { affix: 'Life per Hit', range: [16, 21] },
    { affix: 'Lucky Hit: Up to a Chance to Restore Primary Resource', range: [10, 14, '%'] },
    { affix: 'Critical Strike Damage', range: [40, 50, '%'] },
    { affix: 'Overpower Damage', range: [50, 60, '%'] },
    { affix: 'Vulnerable Damage', range: [30, 40, '%'] },
    { affix: 'Damage Over Time', range: [40, 50, '%'] },
    { affix: 'Damage', range: [20, 25, '%'] },
    { affix: 'Resource Cost Reduction', range: [5, 7, '%'] },
    { affix: 'Strength', range: [70, 84] },
    { affix: 'Fury on Kill', range: [3, 4] },
    { affix: 'Willpower', range: [70, 84] },
    { affix: 'Spirit on Kill', range: [3, 4] },
    { affix: 'Intelligence', range: [70, 84] },
    { affix: 'Essence on Kill', range: [3, 4] },
    { affix: 'Dexterity', range: [70, 84] },
    { affix: 'Energy on Kill', range: [3, 4] },
    { affix: 'Mana on Kill', range: [3, 4] }
];
const weaponTypes = [
    'Dagger', 'Staff', 'Wand', 'Crossbow', 'Bow', 
    'Mace', 'Sword', 'Scythe', 'Axe', 'Two-Handed Sword', 'Two-Handed Axe', 
    'Two-Handed Mace', 'Two-Handed Scythe'
];
const affixOptions = {
    Helm: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Second', range: [67, 161] },
        { affix: 'Maximum Resource', range: [11, 15] },
        { affix: 'Thorns', range: [672, 940] },
        { affix: 'Healing Received', range: [10, 14, '%'] },
        { affix: 'Lucky Hit Chance', range: [8, 10, '%'] },
        { affix: 'Armor', range: [1115, 1150] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'Impairment Reduction', range: [8, 10, '%'] },
        { affix: 'Cooldown Reduction', range: [6, 8, '%'] },
        { affix: 'Strength', range: [70, 84] },
        { affix: 'Fury per Second', range: [4, 5] },
        { affix: 'to Death Blow', range: [2, 3] },
        { affix: 'to Rupture', range: [2, 3] },
        { affix: 'to Steel Grasp', range: [3, 4] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'Spirit per Second', range: [4, 5] },
        { affix: 'to Poison Creeper', range: [3, 4] },
        { affix: 'to Ravens', range: [3, 4] },
        { affix: 'to Wolves', range: [3, 4] },
        { affix: 'to Companion Skills', range: [1, 2] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'Essence per Second', range: [4, 5] },
        { affix: 'to Decrepify', range: [3, 4] },
        { affix: 'to Iron Maiden', range: [3, 4] },
        { affix: 'to Skeletal Mage Mastery', range: [1, 2] },
        { affix: 'to Skeletal Warrior Mastery', range: [1, 2] },
        { affix: 'to Golem Mastery', range: [1, 2] },
        { affix: 'to Curse Skills', range: [1, 2] },
        { affix: 'Dexterity', range: [70, 84] },
        { affix: 'Energy per Second', range: [4, 5] },
        { affix: 'to Imbuement Skills', range: [1, 2] },
        { affix: 'to Cold Imbuement', range: [3, 4] },
        { affix: 'to Poison Imbuement', range: [3, 4] },
        { affix: 'to Shadow Imbuement', range: [3, 4] },
        { affix: 'Mana per Second', range: [4, 5] },
        { affix: 'to Hydra', range: [2, 3] },
        { affix: 'to Ice Blades', range: [2, 3] },
        { affix: 'to Lightning Spear', range: [2, 3] },
        { affix: 'to Conjuration Skills', range: [1, 2] }
    ],
    Chest: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Second', range: [67, 161] },
        { affix: 'Thorns', range: [672, 940] },
        { affix: 'Healing Received', range: [10, 14, '%'] },
        { affix: 'Armor', range: [1115, 1150] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'Impairment Reduction', range: [8, 10, '%'] },
        { affix: 'Strength', range: [70, 84] },
        { affix: 'Fury per Second', range: [4, 5] },
        { affix: 'to Challenging Shout', range: [2, 3] },
        { affix: 'to Ground Stomp', range: [3, 4] },
        { affix: 'to Iron Skin', range: [3, 4] },
        { affix: 'to Rallying Cry', range: [2, 3] },
        { affix: 'to Defensive Skills', range: [1, 2] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'Spirit per Second', range: [4, 5] },
        { affix: 'to Blood Howl', range: [3, 4] },
        { affix: 'to Cyclone Armor', range: [3, 4] },
        { affix: 'to Debilitating Roar', range: [2, 3] },
        { affix: 'to Earthen Bulwark', range: [3, 4] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'Essence per Second', range: [4, 5] },
        { affix: 'to Bone Prison', range: [3, 4] },
        { affix: 'to Corpse Explosion', range: [2, 3] },
        { affix: 'to Blood Mist', range: [2, 3] },
        { affix: 'to Macabre Skills', range: [1, 2] },
        { affix: 'to Skeletal Mage Mastery', range: [1, 2] },
        { affix: 'to Skeletal Warrior Mastery', range: [1, 2] },
        { affix: 'to Golem Mastery', range: [1, 2] },
        { affix: 'Dexterity', range: [70, 84] },
        { affix: 'Energy per Second', range: [4, 5] },
        { affix: 'to Subterfuge Skills', range: [1, 2] },
        { affix: 'to Smoke Grenades', range: [3, 4] },
        { affix: 'to Concealment', range: [2, 3] },
        { affix: 'to Poison Trap', range: [3, 4] },
        { affix: 'to Dark Shroud', range: [3, 4] },
        { affix: 'Mana per Second', range: [4, 5] },
        { affix: 'to Frost Nova', range: [2, 3] },
        { affix: 'to Ice Armor', range: [2, 3] },
        { affix: 'to Teleport', range: [2, 3] },
        { affix: 'to Flame Shield', range: [2, 3] },
        { affix: 'to Defensive Skills', range: [1, 2] }
    ],
    Gloves: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Hit', range: [16, 21] },
        { affix: 'Attack Speed', range: [11, 15, '%'] },
        { affix: 'Critical Strike Chance', range: [8, 10, '%'] },
        { affix: 'Critical Strike Damage', range: [40, 50, '%'] },
        { affix: 'Overpower Damage', range: [50, 60, '%'] },
        { affix: 'Vulnerable Damage', range: [30, 40, '%'] },
        { affix: 'Damage Over Time', range: [40, 50, '%'] },
        { affix: 'Lucky Hit Chance', range: [8, 10, '%'] },
        { affix: 'Lucky Hit: Up to a Chance to Make Enemies Vulnerable for 2 Seconds', range: [22.5, 31.5, '%'] },
        { affix: 'Lucky Hit: Up to a Chance to Restore Primary Resource', range: [10, 14, '%'] },
        { affix: 'Armor', range: [1115, 1150] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'to Core Skills', range: [1, 2] },
        { affix: 'Strength', range: [70, 84] },
        { affix: 'to Double Swing', range: [1, 1] },
        { affix: 'to Hammer of the Ancients', range: [1, 1] },
        { affix: 'to Rend', range: [1, 1] },
        { affix: 'to Upheaval', range: [1, 1] },
        { affix: 'to Whirlwind', range: [1, 1] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'to Landslide', range: [2, 3] },
        { affix: 'to Lightning Storm', range: [2, 3] },
        { affix: 'to Pulverize', range: [2, 3] },
        { affix: 'to Shred', range: [2, 3] },
        { affix: 'to Tornado', range: [2, 3] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'to Blight', range: [1, 1] },
        { affix: 'to Blood Lance', range: [1, 1] },
        { affix: 'to Blood Surge', range: [1, 1] },
        { affix: 'to Bone Spear', range: [1, 1] },
        { affix: 'to Sever', range: [1, 1] },
        { affix: 'to Golem Mastery', range: [1, 2] },
        { affix: 'to Skeletal Mage Mastery', range: [1, 2] },
        { affix: 'to Skeletal Warrior Mastery', range: [1, 2] },
        { affix: 'Dexterity', range: [70, 84] },
        { affix: 'to Barrage', range: [1, 1] },
        { affix: 'to Flurry', range: [1, 1] },
        { affix: 'to Penetrating Shot', range: [1, 1] },
        { affix: 'to Rapid Fire', range: [1, 1] },
        { affix: 'to Twisting Blades', range: [1, 1] },
        { affix: 'to Fireball', range: [2, 3] },
        { affix: 'to Ice Shards', range: [2, 3] },
        { affix: 'to Chain Lightning', range: [2, 3] },
        { affix: 'to Charged Bolts', range: [2, 3] },
        { affix: 'to Incinerate', range: [2, 3] },
        { affix: 'to Frozen Orb', range: [2, 3] }
    ],
    Pants: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Second', range: [67, 161] },
        { affix: 'Thorns', range: [672, 940] },
        { affix: 'Healing Received', range: [10, 14, '%'] },
        { affix: 'Armor', range: [1115, 1150] },
        { affix: 'Dodge Chance', range: [6, 8, '%'] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'Impairment Reduction', range: [8, 10, '%'] },
        { affix: 'to Basic Skills', range: [1, 2] },
        { affix: 'Strength', range: [70, 84] },
        { affix: 'to Lunging Strike', range: [2, 3] },
        { affix: 'to Bash', range: [2, 3] },
        { affix: 'to Frenzy', range: [2, 3] },
        { affix: 'to Flay', range: [2, 3] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'to Earth Spike', range: [1, 1] },
        { affix: 'to Wind Shear', range: [1, 1] },
        { affix: 'to Storm Strike', range: [1, 1] },
        { affix: 'to Maul', range: [1, 1] },
        { affix: 'to Claw', range: [1, 1] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'to Hemorrhage', range: [2, 3] },
        { affix: 'to Decompose', range: [2, 3] },
        { affix: 'to Bone Splinters', range: [2, 3] },
        { affix: 'to Reap', range: [2, 3] },
        { affix: 'to Skeletal Mage Mastery', range: [1, 2] },
        { affix: 'to Skeletal Warrior Mastery', range: [1, 2] },
        { affix: 'to Golem Mastery', range: [1, 2] },
        { affix: 'Dexterity', range: [70, 84] },
        { affix: 'to Heartseeker', range: [2, 3] },
        { affix: 'to Invigorating Strike', range: [2, 3] },
        { affix: 'to Puncture', range: [2, 3] },
        { affix: 'to Blade Shift', range: [2, 3] },
        { affix: 'to Forceful Arrow', range: [2, 3] },
        { affix: 'to Frost Bolt', range: [2, 3] },
        { affix: 'to Spark', range: [2, 3] },
        { affix: 'to Fire Bolt', range: [2, 3] },
        { affix: 'to Arc Lash', range: [2, 3] }
    ],
    Boots: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Second', range: [67, 161] },
        { affix: 'Movement Speed', range: [12.5, 17.5, '%'] },
        { affix: 'Armor', range: [1115, 1150] },
        { affix: 'Dodge Chance', range: [6, 8, '%'] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'Impairment Reduction', range: [8, 10, '%'] },
        { affix: 'Strength', range: [70, 84] },
        { affix: 'Fury per Second', range: [4, 5] },
        { affix: 'to Leap', range: [3, 4] },
        { affix: 'to Charge', range: [3, 4] },
        { affix: 'to War Cry', range: [2, 3] },
        { affix: 'to Kick', range: [3, 4] },
        { affix: 'to Brawling Skills', range: [1, 2] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'Spirit per Second', range: [4, 5] },
        { affix: 'to Hurricane', range: [3, 4] },
        { affix: 'to Boulder', range: [3, 4] },
        { affix: 'to Rabies', range: [3, 4] },
        { affix: 'to Trample', range: [3, 4] },
        { affix: 'to Wrath Skills', range: [1, 2] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'Essence per Second', range: [4, 5] },
        { affix: 'to Bone Spirit', range: [2, 3] },
        { affix: 'to Corpse Tendrils', range: [3, 4] },
        { affix: 'to Skeletal Mage Mastery', range: [1, 2] },
        { affix: 'to Skeletal Warrior Mastery', range: [1, 2] },
        { affix: 'to Golem Mastery', range: [1, 2] },
        { affix: 'to Corpse Skills', range: [1, 2] },
        { affix: 'Dexterity', range: [70, 84] },
        { affix: 'Energy per Second', range: [4, 5] },
        { affix: 'to Dash', range: [3, 4] },
        { affix: 'to Shadow Step', range: [3, 4] },
        { affix: 'to Caltrops', range: [3, 4] },
        { affix: 'to Agility Skills', range: [1, 2] },
        { affix: 'Mana per Second', range: [4, 5] },
        { affix: 'to Meteor', range: [2, 3] },
        { affix: 'to Blizzard', range: [2, 3] },
        { affix: 'to Firewall', range: [2, 3] },
        { affix: 'to Ball Lightning', range: [2, 3] },
        { affix: 'to Mastery Skills', range: [1, 2] }
    ],
    Amulet: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Second', range: [67, 161] },
        { affix: 'Life per Hit', range: [16, 21] },
        { affix: 'Maximum Resource', range: [11, 15] },
        { affix: 'Damage', range: [20, 25, '%'] },
        { affix: 'Attack Speed', range: [11, 15, '%'] },
        { affix: 'Critical Strike Chance', range: [8, 10, '%'] },
        { affix: 'Lucky Hit Chance', range: [8, 10, '%'] },
        { affix: 'Lucky Hit: Up to a Chance to Make Enemies Vulnerable for 2 Seconds', range: [22.5, 31.5, '%'] },
        { affix: 'Movement Speed', range: [12.5, 17.5, '%'] },
        { affix: 'Total Armor', range: [14, 19.5, '%'] },
        { affix: 'Resource Cost Reduction', range: [5, 7, '%'] },
        { affix: 'Cooldown Reduction', range: [6, 8, '%'] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'Strength', range: [70, 84] },
        { affix: 'Fury on Kill', range: [3, 4] },
        { affix: 'to Counteroffensive', range: [1, 2] },
        { affix: 'to Heavy Handed', range: [1, 2] },
        { affix: 'to Slaying Strike', range: [1, 2] },
        { affix: 'to Cut to the Bone', range: [1, 2] },
        { affix: 'to Brute Force', range: [1, 2] },
        { affix: 'to Pit Fighter', range: [1, 2] },
        { affix: 'to No Mercy', range: [1, 2] },
        { affix: 'to Weapon Mastery Skills', range: [1, 2] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'Spirit on Kill', range: [3, 4] },
        { affix: 'to Nature\'s Reach', range: [1, 2] },
        { affix: 'to Wild Impulses', range: [1, 2] },
        { affix: 'to Envenom', range: [1, 2] },
        { affix: 'to Crushing Earth', range: [1, 2] },
        { affix: 'to Resonance', range: [1, 2] },
        { affix: 'to Defiance', range: [1, 2] },
        { affix: 'to Natural Disaster', range: [1, 2] },
        { affix: 'to Heightened Senses', range: [1, 2] },
        { affix: 'to Call of the Wild', range: [1, 2] },
        { affix: 'to Quickshift', range: [1, 2] },
        { affix: 'to Toxic Claws', range: [1, 2] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'Essence on Kill', range: [3, 4] },
        { affix: 'to Gloom', range: [1, 2] },
        { affix: 'to Death\'s Embrace', range: [1, 2] },
        { affix: 'to Terror', range: [1, 2] },
        { affix: 'to Coalesced Blood', range: [1, 2] },
        { affix: 'to Imperfectly Balanced', range: [1, 2] },
        { affix: 'to Compound Fracture', range: [1, 2] },
        { affix: 'to Tides of Blood', range: [1, 2] },
        { affix: 'to Evulsion', range: [1, 2] },
        { affix: 'to Hellbent Commander', range: [1, 2] },
        { affix: 'to Amplify Damage', range: [1, 2] },
        { affix: 'to Fueled by Death', range: [1, 2] },
        { affix: 'Dexterity', range: [70, 84] },
        { affix: 'Energy on Kill', range: [3, 4] },
        { affix: 'to Deadly Venom', range: [1, 2] },
        { affix: 'to Exploit', range: [1, 2] },
        { affix: 'to Frigid Finesse', range: [1, 2] },
        { affix: 'to Malice', range: [1, 2] },
        { affix: 'to Precision Imbuement', range: [1, 2] },
        { affix: 'to Weapon Mastery', range: [1, 2] },
        { affix: 'to Impetus', range: [1, 2] },
        { affix: 'to Concussive', range: [1, 2] },
        { affix: 'to Alchemical Advantage', range: [1, 2] },
        { affix: 'to Trap Mastery', range: [1, 2] },
        { affix: 'Mana on Kill', range: [3, 4] },
        { affix: 'to Hoarfrost', range: [1, 2] },
        { affix: 'to Conjuration Mastery', range: [1, 2] },
        { affix: 'to Permafrost', range: [1, 2] },
        { affix: 'to Icy Touch', range: [1, 2] },
        { affix: 'to Glass Cannon', range: [1, 2] },
        { affix: 'to Elemental Dominance', range: [1, 2] },
        { affix: 'to Inner Flames', range: [1, 2] },
        { affix: 'to Endless Pyre', range: [1, 2] },
        { affix: 'to Devouring Blaze', range: [1, 2] },
        { affix: 'to Shocking Impact', range: [1, 2] }
    ],
    Rings: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Second', range: [67, 161] },
        { affix: 'Life per Hit', range: [16, 21] },
        { affix: 'Damage', range: [20, 25, '%'] },
        { affix: 'Attack Speed', range: [11, 15, '%'] },
        { affix: 'Critical Strike Chance', range: [1.8, 5, '%'] },
        { affix: 'Critical Strike Damage', range: [40, 50, '%'] },
        { affix: 'Overpower Damage', range: [50, 60, '%'] },
        { affix: 'Vulnerable Damage', range: [30, 40, '%'] },
        { affix: 'Damage Over Time', range: [40, 50, '%'] },
        { affix: 'Lucky Hit Chance', range: [4.5, 6, '%'] },
        { affix: 'Lucky Hit: Up to a Chance to Make Enemies Vulnerable for 2 Seconds', range: [22.5, 31.5, '%'] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'Resource Cost Reduction', range: [5, 7, '%'] },
        { affix: 'Strength', range: [70, 84] },
        { affix: 'Fury on Kill', range: [3, 4] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'Spirit on Kill', range: [3, 4] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'Essence on Kill', range: [3, 4] },
        { affix: 'Dexterity', range: [70, 84] },
        { affix: 'Energy on Kill', range: [3, 4] },
        { affix: 'Mana on Kill', range: [3, 4] }
    ],
    Focus: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Hit', range: [16, 21] },
        { affix: 'Maximum Resource', range: [11, 15] },
        { affix: 'Critical Strike Chance', range: [1.8, 5, '%'] },
        { affix: 'Lucky Hit Chance', range: [4.5, 6, '%'] },
        { affix: 'Lucky Hit: Up to a Chance to Restore Primary Resource', range: [10, 14, '%'] },
        { affix: 'Cooldown Reduction', range: [6, 8, '%'] },
        { affix: 'Damage', range: [20, 25, '%'] },
        { affix: 'Resource Cost Reduction', range: [5, 7, '%'] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'Spirit on Kill', range: [3, 4] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'Essence on Kill', range: [3, 4] },
        { affix: 'Mana on Kill', range: [3, 4] }
    ],
    Totem: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Life per Hit', range: [16, 21] },
        { affix: 'Maximum Resource', range: [11, 15] },
        { affix: 'Critical Strike Chance', range: [1.8, 5, '%'] },
        { affix: 'Lucky Hit Chance', range: [4.5, 6, '%'] },
        { affix: 'Lucky Hit: Up to a Chance to Restore Primary Resource', range: [10, 14, '%'] },
        { affix: 'Cooldown Reduction', range: [6, 8, '%'] },
        { affix: 'Damage', range: [20, 25, '%'] },
        { affix: 'Resource Cost Reduction', range: [5, 7, '%'] },
        { affix: 'Willpower', range: [70, 84] },
        { affix: 'Spirit on Kill', range: [3, 4] },
        { affix: 'Intelligence', range: [70, 84] },
        { affix: 'Essence on Kill', range: [3, 4] },
        { affix: 'Mana on Kill', range: [3, 4] }
    ],
    Shield: [
        { affix: 'Maximum Life', range: [638, 873] },
        { affix: 'Thorns', range: [672, 940] },
        { affix: 'Life per Second', range: [67, 161] },
        { affix: 'Damage', range: [20, 25, '%'] },
        { affix: 'Critical Strike Chance', range: [1.8, 5, '%'] },
        { affix: 'Armor', range: [1115, 1150] },
        { affix: 'Resistance to All Elements', range: [8, 10, '%'] },
        { affix: 'Cold Resistance', range: [40, 50, '%'] },
        { affix: 'Fire Resistance', range: [40, 50, '%'] },
        { affix: 'Lightning Resistance', range: [40, 50, '%'] },
        { affix: 'Poison Resistance', range: [40, 50, '%'] },
        { affix: 'Shadow Resistance', range: [40, 50, '%'] },
        { affix: 'Damage Reduction', range: [5.1, 7.3, '%'] },
        { affix: 'Impairment Reduction', range: [8, 10, '%'] },
        { affix: 'Intelligence', range: [70, 84] }
    ]
};

weaponTypes.forEach(type => {
    affixOptions[type] = weaponAffixes;
});


export default affixOptions;
